DROP TABLE zipcodes;

CREATE TABLE zipcodes (RecordNumber int, Country string, City string, Zipcode int)
PARTITIONED BY (State string)
CLUSTERED BY (Zipcode) INTO 5 BUCKETS
ROW FORMAT DELIMITED FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INPATH '/root/zipcodes.csv' INTO TABLE zipcodes;

INSERT OVERWRITE DIRECTORY '/root/hiveOutput'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
SELECT * FROM zipcodes WHERE state='PR' AND zipcode=704;